apiVersion: v1
kind: Namespace
metadata:
  name: linkedcare-system
spec:
  finalizers:
  - kubernetes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.linkedcare.io/name: lk-controller-manager
    control-plane: lk-controller-manager
  name: lk-controller-manager-lk-controller-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicemesh.linkedcare.io
  resources:
  - servicepolicies
  - strategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.k8s.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.linkedcare.io/name: lk-controller-manager
    control-plane: lk-controller-manager
  name: lk-controller-manager-lk-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lk-controller-manager-lk-controller-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: linkedcare-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.linkedcare.io/name: lk-controller-manager
    control-plane: lk-controller-manager
  name: lk-controller-manager
  namespace: linkedcare-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.linkedcare.io/name: lk-controller-manager
      control-plane: lk-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.linkedcare.io/name: lk-controller-manager
        control-plane: lk-controller-manager
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/linkedcare/lc-controller-manager:0.1-v1alpha1
        imagePullPolicy: IfNotPresent
        name: lk-controller-manager
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.linkedcare.io/name: lk-apiserver
    control-plane: lk-apiserver
  name: lk-apiserver
  namespace: linkedcare-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.linkedcare.io/name: lk-apiserver
      control-plane: lk-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.linkedcare.io/name: lk-apiserver
        control-plane: lk-apiserver
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/linkedcare/lc-apiserver:0.1-v1alpha1
        imagePullPolicy: IfNotPresent
        name: lk-apiserver
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/pki
          name: certs
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/kubernetes/pki
          type: DirectoryOrCreate
        name: certs

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.linkedcare.io/name: lk-apiserver
    control-plane: lk-apiserver
  name: lk-apiserver
  namespace: linkedcare-system
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.linkedcare.io/name: lk-apiserver
    control-plane: lk-apiserver
  sessionAffinity: None
  type: ClusterIP
